version: '3.8'
services:
  movies:
    image: gangadhar1/movies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  train:
    image: gangadhar1/train:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  dth:
    image: gangadhar1/dth:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3

  recharge:
    image: gangadhar1/recharge:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3

